spring:
  application:
    name: demo
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI}
        registration:
          keycloak:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
server:
  http:
    port: 8080
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:springboot.p12
    key-store-password: ${CERT_PASS}
    key-alias: springboot